<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f6e1f267-781a-49dd-bc9e-88879158d79c</elementGuidId>
    <imagePath></imagePath>
    <name>button_continue_to_shipping</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/section[1]/main[1]/div[1]/div[2]/div[1]/form[1]/div[1]/div[3]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="MuiButtonBase-root\ MuiButton-root\ MuiButton-contained\ MuiButton-containedPrimary\ MuiButton-sizeLarge\ MuiButton-containedSizeLarge\ MuiButton-root\ MuiButton-contained\ MuiButton-containedPrimary\ MuiButton-sizeLarge\ MuiButton-containedSizeLarge\ css-110xwq5"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'submit') and equals(@text,'CONTINUE TO SHIPPING')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>CONTINUE TO SHIPPING</value>
        <webElementGuid>6c6680f1-9c24-412c-9e3a-263dbb05bfbe</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>submit</value>
        <webElementGuid>6c6680f1-9c24-412c-9e3a-263dbb05bfbe</webElementGuid>
    </webElementProperties>
</WebElementEntity>