<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4285a9af-ca71-44ff-a655-822c55d102d2</elementGuidId>
    <imagePath></imagePath>
    <name>input_payment_method_id</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/section[1]/main[1]/div[1]/div[2]/div[1]/form[1]/div[1]/div[1]/div[1]/label[1]/span[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="PrivateSwitchBase-input\ css-1m9pwf3"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'payment_method_id') and equals(@type,'radio')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>payment_method_id</value>
        <webElementGuid>9a6914e5-9810-4a1f-957b-cecae1ad1a16</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>radio</value>
        <webElementGuid>9a6914e5-9810-4a1f-957b-cecae1ad1a16</webElementGuid>
    </webElementProperties>
</WebElementEntity>